name: Lint and Format
on:
  pull_request:
    branches:
      - main
      - '1.0.0'
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rush Install
        # Pinning to specific commit that has been audited. Only update 3rd party
        # actions' commit hashes if you've audited them
        uses: advancedcsg-open/actions-rush@981bd2de50c1c39dbb8a537e646ee0c410da8638
        with:
          build: true

      - name: Check linting
        run: node common/scripts/install-run-rush.js lint:check -v
